# Databricks notebook source
# MAGIC %md # Main Run Notebook
# MAGIC 
# MAGIC **(!)** Do not use the `Run All` mode on this notebook. 
# MAGIC 
# MAGIC main.py is used to run the codebase in several modes, controlled by the `.Run Mode` widget:
# MAGIC * Pre-Merge: Running of the unit test and integration test suite, prior to GitLab merging
# MAGIC * Post-Merge: Running of the unit test suite, integration test suite, and full pipeline run (post GitLab-to-Databricks merge)
# MAGIC * Pipeline Only: Running of the full pipeline only (General Running)
# MAGIC 
# MAGIC ## How to run the notebook
# MAGIC This notebook is designed to be run line-by-line, with notebook configuration completed through the use of interactive widgets.
# MAGIC The running order for this notebook is defined below:
# MAGIC 1. Run `%run ./src/main_lib` to import the required supporting classes and functions
# MAGIC 2. Run `main.setupNotebook()` to load setup widgets for selecting the run mode
# MAGIC 3. Run `main.configureNotebook()` to populate the associated configurable widget, for selected run mode
# MAGIC 4. Once widgets have been updated to the desired configuration, run `main.runNotebook()`
# MAGIC 
# MAGIC ## Running Notes
# MAGIC * If at any point you wish to reset the notebook or the notebook errors, re-run `main.setupNotebook()` to reset values
# MAGIC 
# MAGIC ## Configurable widgets
# MAGIC The main.py notebook is configured using widgets, created by `main.setupNotebook()` and `main.configureNotebook()`. 
# MAGIC The main setup widget, generated by `main.setupNotebook()`, is the `.Run Mode` widget (defined in the table below).
# MAGIC Widgets created as part of the configuration step `main.configureNotebook()` are defined with their associated run mode(s) below.
# MAGIC 
# MAGIC | Widget Name             | Widget Type | Run Mode                             | Description                                                                                                                                                               | Default Value | Accepted Values                                                              |
# MAGIC |-------------------------|-------------|--------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------|------------------------------------------------------------------------------|
# MAGIC | .Run Mode               | Dropdown    | N/A                                  | Defines the run mode for the main.py notebook                                                                                                                             | Select Mode   | Select Mode, Pre-Merge, Post-Merge, Pipeline Only, Reset Notebook            |
# MAGIC | Cohort Table            | Combobox    | Post-Merge, Pipeline Only            | Defines a pre-existing cohort table name for pipeline runs.<br>If blank, then the cohort table is created in the pipeline run.                                               | None          | String, format of `eligible_cohort_table_YYYY_MM_DD_VERSION`                 |
# MAGIC | Git Version             | Text        | Post-Merge, Pipeline Only            | Git commit hash from the latest master branch (GitLab) or a development string (e.g. dev_s1).<br>Note: This is required and the notebook **will fail** without it specified. | None          | String of commit hash (GitLab) or development hash (e.g. dev_s1)             |
# MAGIC | Params Path             | Text        | Pre-Merge, Post-Merge, Pipeline Only | Location of the params notebook to use for params-bound variables.<br>Note: 'default' indicates the params/params notebook file.                                             | 'default'     | Relative path to params notebook or `'default'` for standard pipeline params |
# MAGIC | Run Pseudo Stage        | Dropdown    | Post-Merge, Pipeline Only            | Run the pseudonymisation preparation stage in the pipeline if True.                                                                                                       | False         | False, True                                                                  |
# MAGIC | Save Integration Tables | Dropdown    | Pre-Merge, Post-Merge, Pipeline Only | Save the tables created from the run_integration_test suite if True.                                                                                                      | False         | False, True                                                                  |
# MAGIC | Unit Test Mode          | Dropdown    | Pre-Merge, Post-Merge                | Run unit tests consecutively (Concurrent) or 4 notebooks in parallel (Parallel).<br>Note: it's recommended to use Concurrent mode when the server is under high load.        | Concurrent    | Concurrent, Parallel                                                         |

# COMMAND ----------

# MAGIC %md ---

# COMMAND ----------

# MAGIC %md ### Widget Reset
# MAGIC Please run the command below when (A) first using the notebook/re-running the notebook setup or (B) to remove all widgets from the notebook.

# COMMAND ----------

import time
dbutils.widgets.removeAll()
time.sleep(5)
print('Widgets reset...')

# COMMAND ----------

# MAGIC %md ---

# COMMAND ----------

# MAGIC %md ### Step 1: Load supporting library utilities
# MAGIC Run the command below to initialise the supporting library for this notebook.

# COMMAND ----------

# MAGIC %run ./src/main_lib

# COMMAND ----------

# MAGIC %md ---

# COMMAND ----------

# MAGIC %md ### Step 2: Setup Notebook
# MAGIC Run the command, only after Step 1, below to setup the main control widget for the `main` notebook.

# COMMAND ----------

main.setupNotebook()

# COMMAND ----------

# MAGIC %md ---

# COMMAND ----------

# MAGIC %md ### Step 3: Configure Notebook
# MAGIC Run the command below, only after Step 2, to configure the run-mode selected for `main` notebook.

# COMMAND ----------

main.configureNotebook(dbutils.widgets.get('.Run Mode'))

# COMMAND ----------

# MAGIC %md ---

# COMMAND ----------

# MAGIC %md ### Step 4: Run Selected Mode
# MAGIC Run the command below, only after Step 3, to run the selected and configured run mode.

# COMMAND ----------

main.runNotebook()

# COMMAND ----------

# MAGIC %md ---

# COMMAND ----------

# MAGIC %md ### END OF NOTEBOOK
